import { MangaItem } from "./types";

export const GLOBAL_TOP_POPULAR: MangaItem[] = [
  {
    "title": "From Goblin to Goblin God",
    "endpoint": "from-goblin-to-goblin-god",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/from-goblin-to-goblin-god/manga_thumbnail-A2-From-Goblin-to-Goblin-God.jpg",
    "type": "Manhua",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "from-goblin-to-goblin-god-chapter-terbaru",
    "genreOrRating": "action, fantasy, reincarnation",
    "views": 694399,
    "rank": 1,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Full-Time Awakening",
    "endpoint": "full-time-awakening",
    "thumb": "https://thumbnail.komiku.to/img/upload/full-time_awakening/img_687dfc3d4330e4.42199864.png",
    "type": "Manhua",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "full-time-awakening-chapter-terbaru",
    "genreOrRating": "action, fantasy",
    "views": 620316,
    "rank": 2,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "One Piece",
    "endpoint": "komik-one-piece-indo",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/komik-one-piece-indo/manga_thumbnail-Komik-One-Piece.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "komik-one-piece-indo-chapter-terbaru",
    "genreOrRating": "action, adventure, comedy",
    "views": 603556,
    "rank": 3,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Tsuihou Sareta Tenshou Juu Kishi wa Game Chishiki de Musou Suru",
    "endpoint": "tsuihou-sareta-tenshou-juu-kishi-wa-game-chishiki-de-musou-suru",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/tsuihou-sareta-tenshou-juu-kishi-wa-game-chishiki-de-musou-suru/manga_thumbnail-tsuihoucover.png",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "tsuihou-sareta-tenshou-juu-kishi-wa-game-chishiki-de-musou-suru-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 559841,
    "rank": 4,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Magic Emperor",
    "endpoint": "magic-emperor",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/magic-emperor/manga_thumbnail-Komik-Magic-Emperor.jpg",
    "type": "Manhua",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "magic-emperor-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 499063,
    "rank": 5,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Disastrous Necromancer",
    "endpoint": "disastrous-necromancer",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/disastrous-necromancer/manga_thumbnail-Head-Disastrous-Necromancer.jpeg",
    "type": "Manhua",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "disastrous-necromancer-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 364855,
    "rank": 6,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Ao Ashi",
    "endpoint": "ao-ashi",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/ao-ashi/manga_thumbnail-Ao-Ashi-Cover.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "ao-ashi-chapter-terbaru",
    "genreOrRating": "drama, school life, seinen",
    "views": 339040,
    "rank": 7,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "One Punch Man",
    "endpoint": "manga-one-punch-man",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/manga-one-punch-man/manga_thumbnail-Komik-One-Punch-Man.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "manga-one-punch-man-chapter-terbaru",
    "genreOrRating": "action, comedy, sci-fi",
    "views": 329665,
    "rank": 8,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Tomb Raider King",
    "endpoint": "tomb-raider-king",
    "thumb": "https://thumbnail.komiku.to/new/img/images/2026/05/28/20260528181515_753fb76625fa3cd5_c0381670.webp",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "tomb-raider-king-chapter-terbaru",
    "genreOrRating": "action, adventure, comedy",
    "views": 265366,
    "rank": 9,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "The Ultimate of All Ages",
    "endpoint": "the-ultimate-of-all-ages",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/the-ultimate-of-all-ages/manga_thumbnail-Manhua-The-Ultimate-of-All-Ages.jpg",
    "type": "Manhua",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "the-ultimate-of-all-ages-chapter-terbaru",
    "genreOrRating": "action, fantasy, historical",
    "views": 263826,
    "rank": 10,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Haikyuu!!",
    "endpoint": "haikyuu-indonesia",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/haikyuu-indonesia/manga_thumbnail-Manga-Haikyuu.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "haikyuu-indonesia-chapter-terbaru",
    "genreOrRating": "comedy, drama, school life",
    "views": 226199,
    "rank": 11,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Return of the Devourer",
    "endpoint": "return-of-the-devourer",
    "thumb": "https://thumbnail.komiku.to/img/upload/return_of_the_devourer/img_695b39b6f0d8f9.73172883.webp",
    "type": "Manhua",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "return-of-the-devourer-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 208371,
    "rank": 12,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Revenge of the Iron-Blooded Sword Hound",
    "endpoint": "revenge-of-the-iron-blooded-sword-hound",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/revenge-of-the-iron-blooded-sword-hound/manga_thumbnail-Head-Revenge-of-the-Iron-Blooded-Sword-Hound.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "revenge-of-the-iron-blooded-sword-hound-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 208331,
    "rank": 13,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Nano Machine",
    "endpoint": "nano-machine",
    "thumb": "https://thumbnail.komiku.to/img/upload/nano_machine/img_693126dac89353.00003505.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "nano-machine-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 201501,
    "rank": 14,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Blue Lock",
    "endpoint": "blue-lock",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/blue-lock/manga_thumbnail-Manga-Blue-Lock.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "blue-lock-chapter-terbaru",
    "genreOrRating": "action, drama, shounen",
    "views": 189075,
    "rank": 15,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Tales of Demons and Gods",
    "endpoint": "tales-demons-gods",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/tales-demons-gods/manga_thumbnail-Komik-Tales-of-Demons-and-Gods.jpg",
    "type": "Manhua",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "tales-demons-gods-chapter-terbaru",
    "genreOrRating": "action, fantasy, shounen",
    "views": 186523,
    "rank": 16,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Mairimashita! Iruma-kun",
    "endpoint": "mairimashita-iruma-kun",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/mairimashita-iruma-kun/manga_thumbnail-Komik-Mairimashita-Iruma-kun.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "mairimashita-iruma-kun-chapter-terbaru",
    "genreOrRating": "comedy, demons, fantasy",
    "views": 184695,
    "rank": 17,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Kanojo no Tomodachi",
    "endpoint": "kanojo-no-tomodachi",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/kanojo-no-tomodachi/manga_thumbnail-Manga-Kanojo-no-Tomodachi.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "kanojo-no-tomodachi-chapter-terbaru",
    "genreOrRating": "adult, drama, ecchi",
    "views": 180828,
    "rank": 18,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Rebirth: Monarch of the Dead",
    "endpoint": "rebirth-monarch-of-the-dead",
    "thumb": "https://thumbnail.komiku.to/new/img/images/2026/08/24/20260824180008_c890fc9b7e5b5a76_64de2534.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "rebirth-monarch-of-the-dead-chapter-terbaru",
    "genreOrRating": "action, adventure, drama",
    "views": 179845,
    "rank": 19,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Sakamoto Days",
    "endpoint": "sakamoto-days",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/sakamoto-days/manga_thumbnail-Manga-Sakamoto-Days.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "sakamoto-days-chapter-terbaru",
    "genreOrRating": "action, comedy, shounen",
    "views": 173596,
    "rank": 20,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Max Level Player",
    "endpoint": "max-level-player",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/max-level-player/manga_thumbnail-Head-Max-Level-Player.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "max-level-player-chapter-terbaru",
    "genreOrRating": "action, adventure, comedy",
    "views": 172973,
    "rank": 21,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "The Regressed Mercenary s Machinations",
    "endpoint": "the-regressed-mercenarys-machinations",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/the-regressed-mercenarys-machinations/manga_thumbnail-A2-The-Regressed-Mercenarys-Machinations.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "the-regressed-mercenarys-machinations-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 160131,
    "rank": 22,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "The World s Best Engineer",
    "endpoint": "the-worlds-best-engineer",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/the-worlds-best-engineer/manga_thumbnail-The-Greatest-Estate-Developer.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "the-worlds-best-engineer-chapter-terbaru",
    "genreOrRating": "action, fantasy, reincarnation",
    "views": 157769,
    "rank": 23,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Return of the First Patriarch: The Strongest Reincarnates into His Descendant 1000 Years Later",
    "endpoint": "return-of-the-first-patriarch",
    "thumb": "https://thumbnail.komiku.to/img/upload/return_of_the_first_patriarch/img_6992e33c4b2928.75017148.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "return-of-the-first-patriarch-chapter-terbaru",
    "genreOrRating": "action, drama, fantasy",
    "views": 148773,
    "rank": 24,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Bleach",
    "endpoint": "bleach",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/bleach/manga_thumbnail-Manga-Bleach.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "bleach-chapter-terbaru",
    "genreOrRating": "action, adventure, comedy",
    "views": 146597,
    "rank": 25,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "God-level Assassin, I m the Shadow",
    "endpoint": "god-level-assassin-im-the-shadow",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/god-level-assassin-im-the-shadow/manga_thumbnail-A2-God-level-Assassin-Im-the-Shadow-scaled.jpg",
    "type": "Manhua",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "god-level-assassin-im-the-shadow-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 139613,
    "rank": 26,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Reincarnation of the Suicidal Battle God",
    "endpoint": "reincarnation-of-the-suicidal-battle-god",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/reincarnation-of-the-suicidal-battle-god/manga_thumbnail-Manwha-Reincarnation-of-the-Suicidal-Battle-God.png",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "reincarnation-of-the-suicidal-battle-god-chapter-terbaru",
    "genreOrRating": "action, fantasy, reincarnation",
    "views": 134646,
    "rank": 27,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Swordmaster s Youngest Son",
    "endpoint": "swordmasters-youngest-son",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/swordmasters-youngest-son/manga_thumbnail-Manhwa-Swordmasters-Youngest-Son.png",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "swordmasters-youngest-son-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 130342,
    "rank": 28,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Apex Future Martial Arts",
    "endpoint": "apex-future-martial-arts",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/apex-future-martial-arts/manga_thumbnail-Apex-Future-Martial-Arts-1.jpg",
    "type": "Manhua",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "apex-future-martial-arts-chapter-terbaru",
    "genreOrRating": "action, drama, fantasy",
    "views": 127514,
    "rank": 29,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "A Disaster-Class Hero Has Returned",
    "endpoint": "a-disaster-class-hero-has-returned",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/a-disaster-class-hero-has-returned/manga_thumbnail-Manhwa-A-Disaster-Class-Hero-Has-Returned.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "a-disaster-class-hero-has-returned-chapter-terbaru",
    "genreOrRating": "action, drama, tragedy",
    "views": 123874,
    "rank": 30,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Childhood Friend Of The Zenith",
    "endpoint": "childhood-friend-of-the-zenith",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/childhood-friend-of-the-zenith/manga_thumbnail-A2-Childhood-Friend-Of-The-Zenith.jpeg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "childhood-friend-of-the-zenith-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 122752,
    "rank": 31,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Became The Patron Of Villains",
    "endpoint": "became-the-patron-of-villains",
    "thumb": "https://thumbnail.komiku.to/img/upload/became_the_patron_of_villains/img_68fb1d5e505ad1.35527108.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "became-the-patron-of-villains-chapter-terbaru",
    "genreOrRating": "action, drama, fantasy",
    "views": 119621,
    "rank": 32,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Grand Blue",
    "endpoint": "31514-grand-blue",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/31514-grand-blue/manga_thumbnail-Komik-Grand-Blue.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "31514-grand-blue-chapter-terbaru",
    "genreOrRating": "comedy, seinen, slice of life",
    "views": 118737,
    "rank": 33,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Black Clover",
    "endpoint": "black-clover-indonesia",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/black-clover-indonesia/manga_thumbnail-Manga-Black-Clover.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "black-clover-indonesia-chapter-terbaru",
    "genreOrRating": "action, comedy, fantasy",
    "views": 117554,
    "rank": 34,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Mato Seihei no Slave",
    "endpoint": "mato-seihei-no-slave",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/mato-seihei-no-slave/manga_thumbnail-Komik-Mato-Seihei-no-Slave.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "mato-seihei-no-slave-chapter-terbaru",
    "genreOrRating": "action, adventure, drama",
    "views": 116746,
    "rank": 35,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Tensei Shitara Slime Datta Ken",
    "endpoint": "tensei-shitara-slime-datta-ken-indo",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/tensei-shitara-slime-datta-ken-indo/manga_thumbnail-Manga-Tensei-Shitara-Slime-Datta-Ken.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "tensei-shitara-slime-datta-ken-indo-chapter-terbaru",
    "genreOrRating": "fantasy, isekai, shounen",
    "views": 115844,
    "rank": 36,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "The strongest assassin gets transferred to another world with his whole class",
    "endpoint": "the-strongest-assassin-gets-transferred-to-another-world-with-his-whole-class",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/the-strongest-assassin-gets-transferred-to-another-world-with-his-whole-class/manga_thumbnail-Head-The-strongest-assassin-gets-transferred-to-another-world-with-his-whole-class.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "the-strongest-assassin-gets-transferred-to-another-world-with-his-whole-class-chapter-terbaru",
    "genreOrRating": "action, fantasy, shounen",
    "views": 114757,
    "rank": 37,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Overgeared New",
    "endpoint": "overgeared-new",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/overgeared-new/manga_thumbnail-Manhua-Overgeared-New.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "overgeared-new-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 111047,
    "rank": 38,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "The Beginning After The End",
    "endpoint": "the-beginning-after-the-end",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/the-beginning-after-the-end/manga_thumbnail-Manhwa-The-Beginning-After-The-End-1.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "the-beginning-after-the-end-chapter-terbaru",
    "genreOrRating": "action, adventure, comedy",
    "views": 110514,
    "rank": 39,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Shangri-La Frontier ~ Kusoge Hunter, Kamige ni Idoman to su~",
    "endpoint": "shangri-la-frontier-kusoge-hunter-kamige-ni-idoman-to-su",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/shangri-la-frontier-kusoge-hunter-kamige-ni-idoman-to-su/manga_thumbnail-Manga-Shangri-La-Frontier-Kusoge-Hunter-Kamige-ni-Idoman-to-su.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "shangri-la-frontier-kusoge-hunter-kamige-ni-idoman-to-su-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 109160,
    "rank": 40,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Kingdom",
    "endpoint": "kingdom",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/kingdom/manga_thumbnail-Komik-Kingdom.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "kingdom-chapter-terbaru",
    "genreOrRating": "action, drama, historical",
    "views": 108334,
    "rank": 41,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Return of the Flowery Mountain Sect",
    "endpoint": "return-of-the-flowery-mountain-sect",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/return-of-the-flowery-mountain-sect/manga_thumbnail-Manhwa-Return-of-the-Flowery-Mountain-Sect.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "return-of-the-flowery-mountain-sect-chapter-terbaru",
    "genreOrRating": "adventure, fantasy, martial arts",
    "views": 107560,
    "rank": 42,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Wind Breaker (NII Satoru)",
    "endpoint": "wind-breaker-nii-satoru-indo",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/wind-breaker-nii-satoru-indo/manga_thumbnail-Head-Wind-Breaker-NII-Satoru.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "wind-breaker-nii-satoru-indo-chapter-terbaru",
    "genreOrRating": "action, comedy, school life",
    "views": 107521,
    "rank": 43,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Martial Peak Part 2",
    "endpoint": "martial-peak-part-2",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/martial-peak-part-2/manga_thumbnail-Manhua-Martial-Peak-Part-2.jpg",
    "type": "Manhua",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "martial-peak-part-2-chapter-terbaru",
    "genreOrRating": "action, adventure, comedy",
    "views": 105514,
    "rank": 44,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Superhuman Era",
    "endpoint": "superhuman-era",
    "thumb": "https://thumbnail.komiku.to/new/img/images/2026/08/16/20260816173015_43575c666e95b792_8e6bfe45.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "superhuman-era-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 105245,
    "rank": 45,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Barbarian s Adventure In A Fantasy World",
    "endpoint": "barbarian---s-adventure-in-a-fantasy-world",
    "thumb": "https://thumbnail.komiku.to/img/upload/barbarian___s_adventure_in_a_fantasy_world/img_688dc3633065e5.44547906.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "barbarian---s-adventure-in-a-fantasy-world-chapter-terbaru",
    "genreOrRating": "action, adventure, comedy",
    "views": 105241,
    "rank": 46,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Solo Max-Level Newbie",
    "endpoint": "131241-solo-max-level-newbie",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/131241-solo-max-level-newbie/manga_thumbnail-Manhwa-Solo-Max-Level-Newbie.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "131241-solo-max-level-newbie-chapter-terbaru",
    "genreOrRating": "action, fantasy, shounen",
    "views": 103685,
    "rank": 47,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Pick Me Up",
    "endpoint": "pick-me-up",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/pick-me-up/manga_thumbnail-Pick-Me-Up-1.png",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "pick-me-up-chapter-terbaru",
    "genreOrRating": "action, adventure, comedy",
    "views": 97001,
    "rank": 48,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Kichiku Eiyuu",
    "endpoint": "kichiku-eiyuu",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/kichiku-eiyuu/manga_thumbnail-Kichiku-Eiyuu-1.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "kichiku-eiyuu-chapter-terbaru",
    "genreOrRating": "adult, ecchi, fantasy",
    "views": 96543,
    "rank": 49,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  },
  {
    "title": "Beyond Myriad Peoples",
    "endpoint": "beyond-myriad-peoples",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/beyond-myriad-peoples/manga_thumbnail-BeyondMyriadCover.png",
    "type": "Manhua",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "beyond-myriad-peoples-chapter-terbaru",
    "genreOrRating": "action, comedy, fantasy",
    "views": 96248,
    "rank": 50,
    "author": "Komikus",
    "uploadedAt": "Hari ini"
  }
];

export const INITIAL_TRENDING: MangaItem[] = [
  {
    "title": "Overgeared New",
    "endpoint": "overgeared-new",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/overgeared-new/manga_thumbnail-Manhua-Overgeared-New.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "overgeared-new-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 111047,
    "rank": 1,
    "author": "Komikus",
    "uploadedAt": "1 jam lalu"
  },
  {
    "title": "One Piece",
    "endpoint": "komik-one-piece-indo",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/komik-one-piece-indo/manga_thumbnail-Komik-One-Piece.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "komik-one-piece-indo-chapter-terbaru",
    "genreOrRating": "action, adventure, comedy",
    "views": 603556,
    "rank": 2,
    "author": "Komikus",
    "uploadedAt": "2 jam lalu"
  },
  {
    "title": "Reincarnation of the Suicidal Battle God",
    "endpoint": "reincarnation-of-the-suicidal-battle-god",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/reincarnation-of-the-suicidal-battle-god/manga_thumbnail-Manwha-Reincarnation-of-the-Suicidal-Battle-God.png",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "reincarnation-of-the-suicidal-battle-god-chapter-terbaru",
    "genreOrRating": "action, fantasy, reincarnation",
    "views": 134646,
    "rank": 3,
    "author": "Komikus",
    "uploadedAt": "3 jam lalu"
  },
  {
    "title": "Rebirth: Monarch of the Dead",
    "endpoint": "rebirth-monarch-of-the-dead",
    "thumb": "https://thumbnail.komiku.to/new/img/images/2026/08/24/20260824180008_c890fc9b7e5b5a76_64de2534.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "rebirth-monarch-of-the-dead-chapter-terbaru",
    "genreOrRating": "action, adventure, drama",
    "views": 179845,
    "rank": 4,
    "author": "Komikus",
    "uploadedAt": "4 jam lalu"
  },
  {
    "title": "Magic Emperor",
    "endpoint": "magic-emperor",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/magic-emperor/manga_thumbnail-Komik-Magic-Emperor.jpg",
    "type": "Manhua",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "magic-emperor-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 499063,
    "rank": 5,
    "author": "Komikus",
    "uploadedAt": "5 jam lalu"
  },
  {
    "title": "Myst, Might, Mayhem (Legend Of Heavenly Chaos Demon)",
    "endpoint": "myst-might-mayhem-legend-of-heavenly-chaos-demon",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/myst-might-mayhem-legend-of-heavenly-chaos-demon/manga_thumbnail-Head-Myst-Might-Mayhem.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "myst-might-mayhem-legend-of-heavenly-chaos-demon-chapter-terbaru",
    "genreOrRating": "action, adventure, demon",
    "views": 93847,
    "rank": 6,
    "author": "Komikus",
    "uploadedAt": "1 jam lalu"
  },
  {
    "title": "A Disaster-Class Hero Has Returned",
    "endpoint": "a-disaster-class-hero-has-returned",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/a-disaster-class-hero-has-returned/manga_thumbnail-Manhwa-A-Disaster-Class-Hero-Has-Returned.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "a-disaster-class-hero-has-returned-chapter-terbaru",
    "genreOrRating": "action, drama, tragedy",
    "views": 123874,
    "rank": 7,
    "author": "Komikus",
    "uploadedAt": "2 jam lalu"
  },
  {
    "title": "The Blind Avenger With A Divine Eye",
    "endpoint": "the-blind-avenger-with-a-divine-eye",
    "thumb": "https://thumbnail.komiku.to/new/img/images/2026/09/29/20260929141513_c41919b0e203a427_7218a255.webp",
    "type": "Manhua",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "the-blind-avenger-with-a-divine-eye-chapter-terbaru",
    "genreOrRating": "action, demon, fantasy",
    "views": 2213,
    "rank": 8,
    "author": "Komikus",
    "uploadedAt": "3 jam lalu"
  },
  {
    "title": "The Regressed Mercenary s Machinations",
    "endpoint": "the-regressed-mercenarys-machinations",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/the-regressed-mercenarys-machinations/manga_thumbnail-A2-The-Regressed-Mercenarys-Machinations.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "the-regressed-mercenarys-machinations-chapter-terbaru",
    "genreOrRating": "action, adventure, fantasy",
    "views": 160131,
    "rank": 9,
    "author": "Komikus",
    "uploadedAt": "4 jam lalu"
  },
  {
    "title": "One Punch Man",
    "endpoint": "manga-one-punch-man",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/manga-one-punch-man/manga_thumbnail-Komik-One-Punch-Man.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "manga-one-punch-man-chapter-terbaru",
    "genreOrRating": "action, comedy, sci-fi",
    "views": 329665,
    "rank": 10,
    "author": "Komikus",
    "uploadedAt": "5 jam lalu"
  }
];

export const INITIAL_ONGOING: MangaItem[] = [
  {
    "title": "Shujinkou no Osananajimi ga, Wakiyaku no Ore ni Gui Gui Kuru",
    "endpoint": "shujinkou-no-osananajimi-ga-wakiyaku-no-ore-ni-gui-gui-kuru",
    "thumb": "https://thumbnail.komiku.to/new/img/images/2026/06/29/20260629194517_8001e773041626df_7a6d2d77.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "shujinkou-no-osananajimi-ga-wakiyaku-no-ore-ni-gui-gui-kuru-chapter-terbaru",
    "genreOrRating": "Manga | Terbaru",
    "views": 9421,
    "rank": 1,
    "author": "Komikus",
    "uploadedAt": "5 menit lalu"
  },
  {
    "title": "Kojiin Tamer",
    "endpoint": "kojiin-tamer",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/kojiin-tamer/manga_thumbnail-A2-Kojiin-Tamer-scaled.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "kojiin-tamer-chapter-terbaru",
    "genreOrRating": "Manga | Terbaru",
    "views": 16436,
    "rank": 2,
    "author": "Komikus",
    "uploadedAt": "6 menit lalu"
  },
  {
    "title": "The Novel s Extra (Remake)",
    "endpoint": "the-novels-extra-remake",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/the-novels-extra-remake/manga_thumbnail-Manhwa-The-Novels-Extra-Remake.jpg",
    "type": "Manhwa",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "the-novels-extra-remake-chapter-terbaru",
    "genreOrRating": "Manhwa | Terbaru",
    "views": 53370,
    "rank": 3,
    "author": "Komikus",
    "uploadedAt": "7 menit lalu"
  },
  {
    "title": "Shangri-La Frontier ~ Kusoge Hunter, Kamige ni Idoman to su~",
    "endpoint": "shangri-la-frontier-kusoge-hunter-kamige-ni-idoman-to-su",
    "thumb": "https://thumbnail.komiku.to/uploads/manga/shangri-la-frontier-kusoge-hunter-kamige-ni-idoman-to-su/manga_thumbnail-Manga-Shangri-La-Frontier-Kusoge-Hunter-Kamige-ni-Idoman-to-su.jpg",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "shangri-la-frontier-kusoge-hunter-kamige-ni-idoman-to-su-chapter-terbaru",
    "genreOrRating": "Manga | Terbaru",
    "views": 109160,
    "rank": 4,
    "author": "Komikus",
    "uploadedAt": "8 menit lalu"
  },
  {
    "title": "Oukoku E Tsuzuku Michi",
    "endpoint": "oukoku-e-tszuku-michi",
    "thumb": "https://thumbnail.komiku.to/new/img/images/2026/03/19/20260319234602_c014daa7d4e2f37a_e03d8f2f.webp",
    "type": "Manga",
    "latestChapter": "Chapter Terbaru",
    "latestChapterEndpoint": "oukoku-e-tsuzuku-michi-chapter-terbaru",
    "genreOrRating": "Manga | Terbaru",
    "views": 43335,
    "rank": 5,
    "author": "Komikus",
    "uploadedAt": "9 menit lalu"
  }
];
